### ISSUE TITLE
Issue on "Category" dropdown list in editing page

### ISSUE THREAD

**Issue by qlero** [Figments/offprint-issue-tracker-old#18]
The "category" dropdown list in the "editing" page of a work is hard-set to "Original Fiction." It means that upon the edition of a work's main page, an inattentive user will possibly overwrite their original work's category with "Original Fiction."
See here:
[Step 1](https://user-images.githubusercontent.com/50065587/66878529-3c6edd00-ef88-11e9-8bd9-a3c2db63c8bc.png)
[Step 2](https://user-images.githubusercontent.com/50065587/66878536-4264be00-ef88-11e9-9251-78d93b55d0ac.png)
[Step 3](https://user-images.githubusercontent.com/50065587/66878538-47297200-ef88-11e9-976e-dfb860c09228.png)
[Step 4](https://user-images.githubusercontent.com/50065587/66878544-4bee2600-ef88-11e9-96ce-e458efd3cf73.png)

**Comment by Figments** [comment]
Fixed pending server restart.
